import manifestJson from './audio-manifest.json'

export interface AudioManifestEntry {
  /** Output MP3 filename. */
  readonly file: string
  /** Source OGG path (relative to the music dir, no extension) this MP3 was transcoded from. */
  readonly src: string
  /** Duration in seconds (from ffprobe at build time). */
  readonly durationSec: number
}

/** Build receipt: track id → media facts. Generated by scripts/build-audio.ts, committed. */
export const audioManifest: Readonly<Record<string, AudioManifestEntry>> = manifestJson

/** Join a base URL and a filename with exactly one separating slash. */
export function joinUrl(base: string, file: string): string {
  const trimmedBase = base.replace(/\/+$/v, '')
  const trimmedFile = file.replace(/^\/+/v, '')
  return `${trimmedBase}/${trimmedFile}`
}

/** Resolve the runtime URL for an audio file (CDN base in prod, `/audio/` in dev). */
export function resolveAudioUrl(file: string): string {
  const base = import.meta.env.VITE_AUDIO_BASE_URL ?? '/audio/'
  return joinUrl(base === '' ? '/audio/' : base, file)
}
